name: .NET
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - name: Getting code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 50

    - name: Generate build number
      if: contains(join(github.event.commits.*.message), 'fix:') || 
          contains(join(github.event.commits.*.message), 'feat:')
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.github_token }}
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
      
    - name: Generate Package Release Notes
      run: |
        echo 'PACKAGE_RELEASE_NOTES<<EOF' >> $env:GITHUB_ENV
        echo '⭐ Last 10 features:' >> $env:GITHUB_ENV
        git log -10 --pretty=format:"- %s %cs" --grep=feat >> $env:GITHUB_ENV
        echo '' >> $env:GITHUB_ENV
        echo '🐞 Last 10 bug fixes:' >> $env:GITHUB_ENV
        git log -10 --pretty=format:"- %s %cs" --grep=fix >> $env:GITHUB_ENV
        echo '' >> $env:GITHUB_ENV
        echo 'EOF' >> $env:GITHUB_ENV
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Run tests
      run: dotnet test --configuration Release
        
    - name: Publish
      if: contains(join(github.event.commits.*.message), 'fix:') || 
          contains(join(github.event.commits.*.message), 'feat:')
      run: dotnet nuget push
        src\**.nupkg
        --api-key ${{ secrets.NUGET_KEY }}
        --source https://api.nuget.org/v3/index.json
        --skip-duplicate
