name: Publish
on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      nuget-trusted-publishing: true
      additional-test-arguments: '--logger GitHubActions'
